CREATE TABLE IF NOT EXISTS imported_movies (
    id BIGSERIAL PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    external_id VARCHAR(128) NOT NULL,
    url VARCHAR(1024),
    primary_title VARCHAR(512),
    original_title VARCHAR(512),
    title_type VARCHAR(128),
    description TEXT,
    primary_image VARCHAR(1024),
    thumbnails TEXT,
    trailer TEXT,
    content_rating VARCHAR(64),
    genres TEXT,
    is_adult BOOLEAN,
    release_date DATE,
    start_year INTEGER,
    end_year INTEGER,
    runtime_minutes INTEGER,
    average_rating DOUBLE PRECISION,
    num_votes INTEGER,
    interests TEXT,
    countries_of_origin TEXT,
    external_links TEXT,
    spoken_languages TEXT,
    filming_locations TEXT,
    production_companies TEXT,
    budget BIGINT,
    gross_worldwide BIGINT,
    metascore INTEGER,
    directors TEXT,
    writers TEXT,
    total_seasons INTEGER,
    total_episodes INTEGER,
    episodes TEXT,
    raw_payload TEXT NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_imported_movies_source_external_id UNIQUE (source, external_id)
);
